  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    ports:
      - '8080:8080'
      - '443:8443'
      - '50000:50000'
    volumes:
      - './data/jenkins/jenkins_data:/jenkins_config'
      - './data/jenkins/jenkins_home:/var/jenkins_home'
    # user
    # user
  # localstack:
  #   container_name: localstack
  #   image: localstack/localstack
  #   ports:
  #     - "4567-4584:4567-4584"
  #     - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
  #   environment:
  #     - SERVICES=${SERVICES- }
  #     - DEBUG=${DEBUG- }
  #     - DATA_DIR=${DATA_DIR- }
  #     - PORT_WEB_UI=${PORT_WEB_UI- }
  #     - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
  #     - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
  #     - DOCKER_HOST=unix:///var/run/docker.sock
  #   volumes:
  #     - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"