version: "3"
services:
  app:
    container_name: app
    restart: always
    build: ./compatibilities/
    ports:
      - "3000:3000"
    environment:
      - APP_PORT=3000
      - MONGO_PORT=27017
      - MONGO_HOST=mongo
      - MONGO_DB=MyDb
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo:4.0.5
    ports:
      - "27017:27017"
    # volumes:
    #   - ./../docker-volumes/data:/data/db
  angular:
    container_name: angular
    restart: always
    build: ./front-end/
    ports:
      - "4200:4200"
    depends_on:
      - app