version: "3"
services:
  app:
    container_name: app
    restart: always
    build: ./
    ports:
      - "3000:3000"
    environment:
      - APP_PORT=3000
    volumes:
      - .:/app
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    container_name: mongodb
    image: mongo:4.0.5
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"